apiVersion: v1
kind: ConfigMap
metadata:
  name: webhooksite-config
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://webhooksite-db:5432/webhooksite
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    server.port=8082
    vaadin.productionMode=true
